DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO(NUMERODEMATRICULA INT PRIMARY KEY, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);


-- para test --
INSERT INTO ODONTOLOGO(NUMERODEMATRICULA, NOMBRE, APELLIDO) VALUES (1234, 'Gerardo', 'Arias');