DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO(NUMERODEMATRICULA INT PRIMARY KEY, NOMBRE VARCHAR(50) NOT NULL, APELLIDO INT NOT NULL);


-- para test --
INSERT INTO ODONTOLOGO(NUMERODEMATRICULA, NOMBRE, APELLIDO) VALUES (12345, 'Gerardo', 'Arias');